### ISSUE TITLE
Hi, There? so this repository is just for mysql and postgresql now？

### ISSUE THREAD

**Issue by yuchenlichuck** [TermerMC/UniversalDB#2]

**Comment by termermc** [comment]
Hello, sorry it has taken me a bit of time to respond, but yes, for not I only have MySQL and PostgreSQL support planned. I don't really intend to develop this framework much more, so I don't expect to explicitly add support for other DB systems, at least anytime soon.

**Comment by yuchenlichuck** [comment]
Ok, Thanks a lot, I get it~
